sequenceDiagram
participant browser
participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->>browser: HTTP 302 / redirect to address defined in Header's location
    deactivate server

    Note right of server: The server posts the text submitted in the form

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: the HTML file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the CSS file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JS file
    deactivate server

    Note right of browser: The server executes JS which has JSON

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json"
    activate server
    server-->>browser: the JSON file, console logged
    deactivate server

    Note right of browser: browser executes event handler: rendering notes on page
